version: '3.7'

services:
  web:
    image: node:16-alpine
    command: sh -c "npm install && npm start"
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ./web:/app

  api:
    image: node:16-alpine
    command: sh -c "npm install && npm start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./api:/app


