version: '3.7'

services:
  web:
    image: node:16-alpine
    command: sh -c "npm install && npm start"
    ports:
      - 8082:8082
    working_dir: /app
    volumes:
      - ./web:/app

  api:
    image: node:16-alpine
    command: sh -c "npm install && npm start"
    ports:
      - 3002:3002
    working_dir: /app
    volumes:
      - ./api:/app


